services:
 client:
  build: client
  restart: unless-stopped
  volumes:
   - ./client/src:/app/src
  ports:
   - 5173:5173
  depends_on:
   - server

 e2e-tests:
  entrypoint: "/bin/true"
  build: e2e-tests
  network_mode: host
  depends_on:
   - client
  volumes:
   - ./e2e-tests/tests:/app/tests

 server:
  build: server
  restart: unless-stopped
  volumes:
   - ./server:/app
  ports:
   - 8000:8000
